### ISSUE TITLE
php 5.6: error build on version unit 1.22

### ISSUE THREAD

**Issue by Izorkin** [nginx/unit#525]
Build log:
```
gcc -c -pipe -fPIC -fvisibility=hidden -O -W -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wmissing-prototypes -Werror -g    -I src -I build \
-I/nix/store/hh9z1kzgcns2349j93s49m755rfpj8kf-php-5.6.40-dev/include/php -I/nix/store/hh9z1kzgcns2349j93s49m755rfpj8kf-php-5.6.40-dev/include/php/main -I/nix/store/hh9z1kzgcns2349$
-MMD -MF build/src/nxt_php_sapi-php56.dep -MT build/src/nxt_php_sapi-php56.o \
-o build/src/nxt_php_sapi-php56.o src/nxt_php_sapi.c
src/nxt_php_sapi.c: In function 'nxt_php_execute':
src/nxt_php_sapi.c:1044:9: error: too few arguments to function 'php_handle_auth_data'
 1044 |         php_handle_auth_data(nxt_unit_sptr_get(&f->value));
      |         ^~~~~~~~~~~~~~~~~~~~
In file included from src/nxt_php_sapi.c:9:
/nix/store/hh9z1kzgcns2349j93s49m755rfpj8kf-php-5.6.40-dev/include/php/main/php_main.h:48:12: note: declared here
   48 | PHPAPI int php_handle_auth_data(const char *auth TSRMLS_DC);
      |            ^~~~~~~~~~~~~~~~~~~~
make: *** [build/Makefile:1788: build/src/nxt_php_sapi-php56.o] Error 1

```

**Comment by VBart** [comment]
Please try the following patch:
```diff
diff --git a/src/nxt_php_sapi.c b/src/nxt_php_sapi.c
--- a/src/nxt_php_sapi.c
+++ b/src/nxt_php_sapi.c
@@ -1041,7 +1041,11 @@ nxt_php_execute(nxt_php_run_ctx_t *ctx, 
     if (r->authorization_field != NXT_UNIT_NONE_FIELD) {
         f = r->fields + r->authorization_field;
 
+#ifdef NXT_PHP7
         php_handle_auth_data(nxt_unit_sptr_get(&f->value));
+#else
+        php_handle_auth_data(nxt_unit_sptr_get(&f->value) TSRMLS_CC);
+#endif
 
     } else {
         SG(request_info).auth_digest = NULL;
```

**Comment by Izorkin** [comment]
@VBart thansk, pacth working!
