### ISSUE TITLE
PHP 5.6-7.1 build with clang fails

### ISSUE THREAD

**Issue by avkarenow** [nginx/unit#613]
Hello,

PHP modules for versions 5.6, 7.0 and 7.1 fail to build with Clang 11.0.1 (default compiler) on FreeBSD 13.0.
GCC 10.3.0 works fine.

```
checking for PHP embed SAPI
In file included from build/autotest.c:2:
In file included from /usr/local/php70/include/php/main/php.h:35:
In file included from /usr/local/php70/include/php/Zend/zend.h:342:
/usr/local/php70/include/php/Zend/zend_operators.h:119:14: error: implicit conversion from 'long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Werror,-Wimplicit-const-int-float-conversion]
        } else if (!ZEND_DOUBLE_FITS_LONG(d)) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/php70/include/php/Zend/zend_operators.h:100:45: note: expanded from macro 'ZEND_DOUBLE_FITS_LONG'
#       define ZEND_DOUBLE_FITS_LONG(d) (!((d) >= ZEND_LONG_MAX || (d) < ZEND_LONG_MIN))
                                               ~~ ^~~~~~~~~~~~~
/usr/local/php70/include/php/Zend/zend_long.h:37:24: note: expanded from macro 'ZEND_LONG_MAX'
# define ZEND_LONG_MAX INT64_MAX
                       ^~~~~~~~~
/usr/include/x86/_stdint.h:90:19: note: expanded from macro 'INT64_MAX'
#define INT64_MAX       0x7fffffffffffffff
                        ^~~~~~~~~~~~~~~~~~
1 error generated.
----------

    #include <php.h>
    #include <php_main.h>

    int main() {
        php_module_startup(NULL, NULL, 0);
        return 0;
    }
----------
cc -pipe -fPIC -fvisibility=hidden -O -W -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -fstrict-aliasing -Wstrict-overflow=5 -Wmissing-prototypes -Werror -g -I/usr/local/php70/include/php -I/usr/local/php70/include/php/main -I/usr/local/php70/include/php/TSRM -I/usr/local/php70/include/php/Zend -I/usr/local/php70/include/php/ext -I/usr/local/php70/include/php/ext/date/lib -o build/autotest build/autotest.c -lphp7 -L/usr/local/php70/lib -Wl,-rpath,/usr/local/php70/lib -L/usr/local/lib
----------
```

PHP 7.2, 7.3, 7.4 and 8.0 modules were built without problems.

**Comment by VBart** [comment]
The bug is in the PHP header files. We don't control them. It's better to report to PHP, but I guess that won't be fixed as PHP 7.2 or earlier are out of any support. See: https://www.php.net/supported-versions.php

You may have better luck compiling it, if you instruct compiler to ignore warnings:
```
./configure --cc-opt="-Wno-error"

**Comment by avkarenow** [comment]
Running configure with --cc-opt="-Wno-error" helps. Thanks!

Maybe it's a good idea to just ignore warnings by default for Clang and PHP 5.6, 7.0 and 7.1 modules?

**Comment by tippexs** [comment]
In general speaking switching off errors / warnings before even looking at them is not a good idea. In this case it totally make sense.
