### ISSUE TITLE
nginx-unit does not compile with glibc-2.34

### ISSUE THREAD

**Issue by mpagano** [nginx/unit#580]
from src/nxt_main.h:31,
                 from src/nxt_errno.c:7:
src/nxt_thread.h:145:6: error: missing binary operator before token "("
  145 | #if (PTHREAD_STACK_MIN)
      |      ^~~~~~~~~~~~~~~~~
In file included from /usr/include/bits/local_lim.h:81,
                 from /usr/include/bits/posix1_lim.h:161,

**Comment by mar0x** [comment]
Please use solution from #576 until we merge it.
