### ISSUE TITLE
Issue with Docker image

### ISSUE THREAD

**Issue by noah-friedman** [nginx/unit#509]
I can't actually build using the go1.11-dev docker image because it is missing the libc6-dev package. This results in a compilation error.

**Comment by thresheek** [comment]
Hi @noah-friedman I believe this issue is now fixed in `nginx/unit:1.22.0-go1.15 `:

```
$ docker run -ti --rm nginx/unit:1.22.0-go1.15 bash
root@724c3c27cab6:/go# dpkg -l | grep -i libc6
ii  libc6:amd64                2.28-10                     amd64        GNU C Library: Shared libraries
ii  libc6-dev:amd64            2.28-10                     amd64        GNU C Library: Development Libraries and Header Files
```
